# -*- coding: utf-8 -*-
"""Untitled0.ipynb


Automatically generated by Colab.


Original file is located at
    [https://colab.research.google.com/drive/12W95otyHUoIa9oiMVQZxFSR0T35KFbri](https://colab.research.google.com/drive/12W95otyHUoIa9oiMVQZxFSR0T35KFbri)
"""
import torch
from torch.utils.data import DataLoader, Subset, random_split
from torchvision import datasets, transforms, models
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Non-GUI backend, so it must be before pyplot import
import matplotlib.pyplot as plt
import cv2
from PIL import Image
import torchvision.transforms.functional as TF


print("Step 1: imports done")



# Download GTSRB
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225])
])


full_ds = datasets.GTSRB(root='./data', split='train', download=True, transform=transform)
print("Step 2: dataset loaded")


all_targets = []
for _, target in full_ds:
    all_targets.append(target)


print("Step 3: targets collected")


print(f"Full: {len(full_ds)} images, Classes: {len(np.unique(all_targets))}")



NUM_CLASSES = 43
IMAGES_PER_CLASS = 232  # 120 per class = ~5000 total


subset_indices = []
all_targets_array = np.array(all_targets)  


for cls in range(NUM_CLASSES):
    cls_indices = np.where(all_targets_array == cls)[0].tolist()
    selected = cls_indices[:IMAGES_PER_CLASS]
    subset_indices.extend(selected)


print(f"Total images: {len(subset_indices)}")
print(f"Per class: {IMAGES_PER_CLASS}")


print("Step 4: subset built")


total = len(subset_indices)
train_size = int(0.8 * total)
val_size = total - train_size


np.random.seed(42)
np.random.shuffle(subset_indices)


train_indices = subset_indices[:train_size]
val_indices = subset_indices[train_size:]


train_ds = Subset(full_ds, train_indices)
val_ds = Subset(full_ds, val_indices)


train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=32, shuffle=False)


print(f"Train: {len(train_ds)} images")  # ~4100
print(f"Val: {len(val_ds)} images")      # ~1000


device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using: {device}")


model = models.resnet18(weights=None)



model.fc = nn.Sequential(
    nn.Dropout(0.3),           # Randomly turns off 30% of neurons
    nn.Linear(model.fc.in_features, 43)
)


model = model.to(device)


criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0005)  # Slower learning rate


print("Model ready!")


best_val_acc = 0


for epoch in range(15):  
    # Training
    model.train()
    total_loss = 0
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()


    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()


    val_acc = 100 * correct / total
    print(f"Epoch {epoch+1}/15 - Loss: {total_loss/len(train_loader):.4f} - Val Acc: {val_acc:.2f}%")


print("Training done!")


model.eval()
correct = 0
total = 0


with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()


print(f"ResNet-18 Single Frame Clean Accuracy: {100 * correct / total:.2f}%")
print(f"Total val images: {total}")


torch.save(model.state_dict(), 'resnet18_baseline_1000.pth')
print("Model saved!")



raw_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()  # No normalization here
])


raw_ds = datasets.GTSRB(root='./data', split='train', download=False, transform=raw_transform)

"""
def generate_8_frames(pil_image, attack=False):
    frames = []
    img = np.array(pil_image)
    h, w = img.shape[:2]

    attack_frames = [1, 3, 5, 7]

    for i in range(8):
        frame = img.copy()

        angle = np.random.uniform(-10, 10)
        M = cv2.getRotationMatrix2D((w//2, h//2), angle, 1.0)
        frame = cv2.warpAffine(frame, M, (w, h))

        brightness = np.random.uniform(0.8, 1.2)
        frame = np.clip(frame * brightness, 0, 255).astype(np.uint8)

        if attack and i in attack_frames:
            patch_size = int(w * 0.65)         # 65% coverage
            x1 = (w - patch_size) // 2         # centered
            y1 = (h - patch_size) // 2
            x2 = x1 + patch_size
            y2 = y1 + patch_size

            # High contrast noise
            noise = np.random.randint(0, 255, (y2-y1, x2-x1, 3), dtype=np.uint8)
            frame[y1:y2, x1:x2] = noise

            # Extra: darken the rest of the frame to remove context
            mask = np.ones_like(frame, dtype=np.float32) * 0.3
            mask[y1:y2, x1:x2] = 1.0
            frame = (frame * mask).astype(np.uint8)

        frames.append(frame)

    return frames
"""

def generate_8_frames(pil_image, attack=False):
    frames = []
    img = np.array(pil_image)
    h, w = img.shape[:2]

    attack_frame_indices = [1, 2, 3, 5, 7]

    for i in range(8):
        frame = img.copy()

        # Standard rotation and brightness
        angle = np.random.uniform(-10, 10)
        M = cv2.getRotationMatrix2D((w // 2, h // 2), angle, 1.0)
        frame = cv2.warpAffine(frame, M, (w, h))
        brightness = np.random.uniform(0.8, 1.2)
        
        frame = np.clip(frame * brightness, 0, 255).astype(np.uint8)

        if attack and i in attack_frame_indices:
            attack_type = i % 2  # Alternate between attack types

            if attack_type == 0:
                # Attack A — Full image noise + color inversion
                full_noise = np.random.randint(0, 255, (h, w, 3), dtype=np.uint8)
                frame = full_noise.copy()
                frame = cv2.bitwise_not(frame)

            else:
                # Attack B — Shadow + heavy blur
                frame = frame.astype(np.float32)
                frame[h//3:, :] *= 0.15  # Very dark shadow
                frame = frame.astype(np.uint8)
                frame = cv2.GaussianBlur(frame, (31, 31), 0)

        frames.append(frame)

    return frames


print("Deterministic attack ready!")




# Get raw image (not normalized)
raw_image, sample_label = raw_ds[subset_indices[0]]
sample_pil = transforms.ToPILImage()(raw_image)  # Safe now - not normalized


clean_frames = generate_8_frames(sample_pil, attack=False)
attacked_frames = generate_8_frames(sample_pil, attack=True)


fig, axes = plt.subplots(2, 8, figsize=(20, 5))
fig.suptitle('Top: Clean    Bottom: Attacked', fontsize=12)


for i in range(8):
    axes[0, i].imshow(clean_frames[i])
    axes[0, i].set_title(f'Frame {i+1}')
    axes[0, i].axis('off')
    axes[1, i].imshow(attacked_frames[i])
    axes[1, i].set_title(f'Frame {i+1}')
    axes[1, i].axis('off')


plt.tight_layout()
plt.savefig('frames_visualization.png')
plt.close()
print("Plot saved as frames_visualization.png")



def majority_vote(model, frames, device):
    model.eval()
    all_probs = []


    # This normalization matches what ResNet was trained on
    preprocess = transforms.Compose([
        transforms.ToPILImage(),
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])


    with torch.no_grad():
        for frame in frames:
            tensor = preprocess(frame).unsqueeze(0).to(device)
            output = model(tensor)
            probs = torch.softmax(output, dim=1)
            all_probs.append(probs.cpu().numpy())


    avg_probs = np.mean(all_probs, axis=0)
    final_prediction = np.argmax(avg_probs)
    return final_prediction


print("Majority vote ready!")


correct_clean = 0
correct_attacked = 0
total = 0


for idx in val_indices:
    raw_image, true_label = raw_ds[idx]
    pil_image = transforms.ToPILImage()(raw_image)


    clean_frames = generate_8_frames(pil_image, attack=False)
    attacked_frames = generate_8_frames(pil_image, attack=True)


    clean_pred = majority_vote(model, clean_frames, device)
    attacked_pred = majority_vote(model, attacked_frames, device)


    if clean_pred == true_label:
        correct_clean += 1
    if attacked_pred == true_label:
        correct_attacked += 1


    total += 1


print(f"Total val images tested: {total}")
print(f"Single Frame ResNet-18 - Clean: {100 * correct / len(val_indices):.2f}%")
print(f"Majority Vote - Clean Accuracy: {100 * correct_clean / total:.2f}%")
print(f"Majority Vote - Attacked Accuracy: {100 * correct_attacked / total:.2f}%")


